version: 2.1

orbs:
  node: circleci/node@5.0.3
  browser-tools: circleci/browser-tools@1.4.0

jobs:
  test:
    parameters:
      version:
        default: 'current'
        description: Node.JS version to install
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>-browsers
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          install-geckodriver: false
      - run:
          command: |
            google-chrome --version
            firefox --version
          name: Check install
      - node/install-packages:
          override-ci-command: yarn install
      - run: node --version

      - run:
          name: Install e2e dependencies
          command: cd test/dev-and-e2e && yarn install && cd ../../
      # necessary for syncing to test folder
      - run: sudo apt update
      - run: sudo apt-get install -y rsync
      - run: yarn build
      - run: yarn lint:ci
      - run: yarn test:unit
      - run: $(yarn bin)/cross-env-shell DEBUG=imgix:* yarn run test:e2e:ci

  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn build
      - run: npx semantic-release

workflows:
  test:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - 'current'
                - 'lts'

      - deploy:
          requires:
            - test
