version: 2.1

orbs:
  node: circleci/node@5.0.0
  browser-tools: circleci/browser-tools@1.2.4

jobs:
  test:
    parameters:
      version:
        default: 'stable'
        description: Node.JS version to install
        type: string
    docker:
      - image: cimg/node:<<parameters.version>>-browsers
    resource_class: large
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          install-geckodriver: false
      - run:
          command: |
            google-chrome --version
            firefox --version
          name: Check install
      - when:
          condition:
            equal: ['current', <<parameters.version>>]
          steps:
            # Prevents build error on stable node version
            - run: echo 'export NODE_OPTIONS=--openssl-legacy-provider' >> $BASH_ENV
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd test/dev-and-e2e && yarn install --frozen-lockfile && cd ../../
      - run: yarn build
      - run: yarn lint:ci
      - run: ./node_modules/.bin/cross-env-shell DEBUG=imgix:* yarn test
  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

workflows:
  test:
    jobs:
      - test:
          version: 'current'
      # - deploy:
      #     requires:
      #       - test
