version: 2.1

orbs:
  node: circleci/node@5.0.0
  cypress: cypress-io/cypress@1

jobs:
  test:
    parameters:
      version:
        default: 'stable'
        description: Node.JS version to install
        type: string
    docker:
      - image: cimg/node:<<parameters.version>
    resource_class: medium
    steps:
      - checkout
      - when:
          condition:
            equal: ['current', <<parameters.version>>]
          steps:
            # Prevents build error on stable node version
            - run: echo 'export NODE_OPTIONS=--openssl-legacy-provider' >> $BASH_ENV
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: cd test/dev-and-e2e && yarn install --frozen-lockfile && cd ../../
      - run: yarn build
      - run: yarn lint:ci
      - run: yarn test:unit
  deploy:
    docker:
      - image: cimg/node:current
    steps:
      - checkout
      - node/install-packages
      - run: npx semantic-release

executors:
  cypress-with-env-var:
    docker:
      - image: 'cypress/base'
    environment:
      DEBUG: imgix:*
      BAR: bar

workflows:
  test:
    jobs:
      - test:
          version: 'current'
      - cypress/run:
          yarn: true
          executor: cypress-with-env-var
          install-command: yarn install --frozen-lockfile && cd test/dev-and-e2e && yarn install --frozen-lockfile
          build: yarn build
      - deploy:
          requires:
            - test
            - cypress/run
